version: "3"

services:
  user-service:
    build:
      context: .
      dockerfile: deployment/prod-dockerfiles/Dockerfile.user-service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      PRISMA_DATABASE_URL: ${PRISMA_DATABASE_URL}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}

  question-service:
    build:
      context: .
      dockerfile: deployment/prod-dockerfiles/Dockerfile.question-service
    container_name: question-service
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
      MONGO_ATLAS_URL: ${MONGO_ATLAS_URL}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}

  admin-service:
    build:
      context: .
      dockerfile: deployment/prod-dockerfiles/Dockerfile.admin-service
    container_name: admin-service
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}

  frontend:
    build:
      context: .
      dockerfile: deployment/prod-dockerfiles/Dockerfile.frontend
      args:
        NEXT_PUBLIC_FRONTEND_FIREBASE_CONFIG_ARG: ${NEXT_PUBLIC_FRONTEND_FIREBASE_CONFIG}
    container_name: frontend
    ports:
      - "3000:3000"
