version: "3"

services:
  user-service:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.user-service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      PRISMA_DATABASE_URL: ${DATABASE_URL}

  matching-service:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.matching-service
    container_name: matching-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      PRISMA_DATABASE_URL: ${DATABASE_URL}

  collaboration-service:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.collaboration-service
    container_name: collaboration-service
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      PRISMA_DATABASE_URL: ${DATABASE_URL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_API_KEY: ${TWILIO_API_KEY}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}

  question-service:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.question-service
    container_name: question-service
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
      MONGO_ATLAS_URL: ${MONGO_ATLAS_URL}

  admin-service:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.admin-service
    container_name: admin-service
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}

  gateway:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.gateway
    container_name: gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}

  frontend:
    build:
      context: .
      dockerfile: deployment/dev-dockerfiles/Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      GATEWAY_ADDRESS: "http://localhost:4000/"
      NEXT_PUBLIC_FRONTEND_FIREBASE_CONFIG: ${NEXT_PUBLIC_FRONTEND_FIREBASE_CONFIG}
