version: "3"

services:
  user-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.user-service
    ports:
      - "5001:5001" # Adjust this port mapping according to your service
    environment:
      - PORT=5001

  frontend:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.frontend
    ports:
      - "3000:3000"
