version: "3"

services:
  user-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.user-service
    ports:
      - "5001:5001" # Adjust this port mapping according to your service
    environment:
      - PORT=5001

  matching-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.matching-service
    ports:
      - "5002:5002" # Adjust this port mapping according to your service
    environment:
      - PORT=5002

  collaboration-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.collaboration-service
    ports:
      - "5003:5003" # Adjust this port mapping according to your service
    environment:
      - PORT=5003

  question-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.question-service
    ports:
      - "5004:5004" # Adjust this port mapping according to your service
    environment:
      - PORT=5004

  frontend:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.frontend
    ports:
      - "3000:3000"
