version: "3"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  firebase_admin_service_account:
    file: ./secrets/firebase_admin_service_account.json

services:
  postgres-db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: peerprepdb
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    secrets:
      - postgres_password

  gateway:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      FIREBASE_SERVICE_ACCOUNT: /run/secrets/firebase_admin_service_account
    secrets:
      - firebase_admin_service_account

  user-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.user-service
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      POSTGRES_USER: postgres
      POSTGRES_DB: peerprepdb
      POSTGRES_PASSWORD: /run/secrets/postgres_password

  matching-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.matching-service
    ports:
      - "5002:5002"
    environment:
      PORT: 5002

  collaboration-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.collaboration-service
    ports:
      - "5003:5003"
    environment:
      PORT: 5003

  question-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.question-service
    ports:
      - "5004:5004"
    environment:
      PORT: 5004

  admin-service:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.admin-service
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      FIREBASE_SERVICE_ACCOUNT: /run/secrets/firebase_admin_service_account
    secrets:
      - firebase_admin_service_account

  frontend:
    build:
      context: .
      dockerfile: deployment/dockerfiles/Dockerfile.frontend
    ports:
      - "3000:3000"
