version: "3"

services:
  postgres-db:
    image: postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: peerprepdb-user-service-systemtest
      POSTGRES_PASSWORD: ${PRISMA_DATABASE_PASSWORD}
