# Use the base image
FROM peerprep-base:latest

# Set working directory
WORKDIR /app/services/matching-service

# Copy root level package.json, yarn.lock, and the entire services directory
COPY package.json yarn.lock /app/
COPY services/matching-service /app/services/matching-service
COPY prisma ./prisma/

RUN yarn prisma generate

# Install all dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Compile service from TypeScript to JavaScript
RUN yarn build

# Re-install production-only dependencies
RUN yarn install --frozen-lockfile --production --cwd /app

# Run service
CMD [ "yarn", "workspace", "matching-service", "start" ]
