apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "gateway-backend-config"}'
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
    - name: "4002"
      port: 4002
      targetPort: 4002
    - name: "4003"
      port: 4003
      targetPort: 4003
    # Needed for health check
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
