apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gateway-backend-config
spec:
  healthCheck:
    timeoutSec: 3
    type: HTTP
    requestPath: /healthz
    port: 8080
  customRequestHeaders:
    headers:
      - "Access-Control-Allow-Origin: https://www.codeparty.org"
