apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/cs3219-project-default: "true"
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: FIREBASE_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: firebase-service-account
                  key: firebase-service-account
            - name: PORT
              value: "4000"
            - name: FRONTEND_ADDRESS
              value: "http://www.codeparty.org:3000"
          image: asia-southeast1-docker.pkg.dev/peerprep-group11-prod/codeparty-prod-images/gateway:latest
          name: gateway
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources: 
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "100m"
      restartPolicy: Always
status: {}
