apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-service
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/cs3219-project-default: "true"
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: database-url
            - name: PORT
              value: "5001"
          image: asia-southeast1-docker.pkg.dev/peerprep-group11-dev/codeparty-prod-images/user-service:latest
          name: user-service
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
