# Use the base image
FROM peerprep-base:latest

# Set working directory
WORKDIR /app/services/matching-service

# Copy root level package.json, yarn.lock, and the entire services directory
COPY package.json yarn.lock /app/
COPY services/matching-service /app/services/matching-service
COPY prisma ./prisma/

RUN yarn prisma generate

# Install dependencies using Yarn Workspaces
RUN yarn install --cwd /app

# Run service
CMD [ "yarn", "workspace", "matching-service", "dev" ]
