# Use the base image
FROM peerprep-base:latest

# Set working directory
WORKDIR /app/services/gateway

# Copy root level package.json, yarn.lock, and the entire services directory
COPY package.json yarn.lock /app/
COPY services/gateway /app/services/gateway
COPY prisma ./prisma/

RUN yarn prisma generate

# Install dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Run service
CMD [ "yarn", "workspace", "gateway", "dev" ]
