# Use the base image
FROM peerprep-base:latest

# Set working directory
WORKDIR /app/services/collaboration-service

# Copy root level package.json, yarn.lock, and the entire services directory
COPY package.json yarn.lock /app/
COPY services/collaboration-service /app/services/collaboration-service
COPY prisma ./prisma/
COPY utils /app/utils/

RUN yarn prisma generate

# Install dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Run service
CMD [ "yarn", "workspace", "collaboration-service", "dev" ]
