# Use the base image you created above
FROM peerprep-base:latest

# Set working directory for frontend
WORKDIR /app/frontend

# Copy frontend files
COPY frontend .
COPY utils /app/utils/

# Install dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Start command for the frontend
CMD [ "yarn", "workspace", "frontend", "dev" ]


