# Use the base image
FROM peerprep-base:latest

# Copy utils
COPY utils /app/utils/

# Set working directory
WORKDIR /app/services/collaboration-service

# Copy the entire services directory and prisma
COPY services/collaboration-service /app/services/collaboration-service
COPY prisma ./prisma/

# Install all dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Generate the prisma client
RUN yarn prisma generate

# Run service
CMD [ "yarn", "workspace", "collaboration-service", "dev" ]
