# Use the base image you created above
FROM peerprep-base:latest

# Copy utils
COPY utils /app/utils/

# Set working directory for frontend
WORKDIR /app/frontend

# Copy the entire frontend directory and prisma
COPY frontend /app/frontend
COPY prisma ./prisma/

# Install all dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Generate the prisma client
RUN yarn prisma generate

# Start command for the frontend
CMD [ "yarn", "workspace", "frontend", "dev" ]


