# Use the base image you created above
FROM peerprep-base:latest

# Copy utils
COPY utils /app/utils/

# Set working directory for frontend
WORKDIR /app/frontend

# Copy root level package.json, yarn.lock, and the entire frontend directory
COPY package.json yarn.lock /app/
COPY frontend /app/frontend
COPY prisma ./prisma/

RUN yarn prisma generate

# Install dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Start command for the frontend
CMD [ "yarn", "workspace", "frontend", "dev" ]


