# Use the base image
FROM peerprep-base:latest

# Set working directory
WORKDIR /app/services/matching-service

# Copy the entire services directory and prisma
COPY services/matching-service /app/services/matching-service
COPY prisma ./prisma/

# Install all dependencies using Yarn Workspaces
RUN yarn install --frozen-lockfile --cwd /app

# Generate the prisma client
RUN yarn prisma generate

# Run service
CMD [ "yarn", "workspace", "matching-service", "dev" ]
