name: Continuous Integration

on:
  push:
    branches-ignore:
      - gh-pages

env:
  NODE_VER: '18.x'
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_VER: 11
  FIREBASE_AUTH_EMULATOR_HOST: "127:0:0:1:9099"
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
  DATABASE_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}

jobs:
  mainbuild:
    name: CI on Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VER }}

    - name: Install dependencies with immutable lockfile
      run: yarn install --frozen-lockfile

    - name: Run linting
      run: |
        yarn workspace user-service lint
        yarn workspace admin-service lint
        yarn workspace gateway lint

    - name: Run unit tests
      run: |
        yarn workspace user-service test
        yarn workspace admin-service test:ci

    - name: Run system tests
      run: |
        yarn workspace user-service systemtest:ci
        yarn workspace admin-service systemtest:ci
